<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        // Instrutor: tenta pegar um usuário com role "instructor", senão pega o primeiro usuário
        $instructorId = DB::table('users')->where('role', 'instructor')->value('id')
            ?? DB::table('users')->orderBy('id')->value('id')
            ?? 1;

        /**
         * CategorySeeder e SubCategorySeeder geram slug usando Str::slug($name).
         * Então aqui nós fazemos o mesmo: trabalhamos com NOME e convertemos para slug.
         */

        // Categories: slug => {id, slug}
        $categories = DB::table('categories')
            ->select('id', 'slug')
            ->get()
            ->keyBy('slug');

        // SubCategories: index rápido por "category_id:slug" => subcategory_id
        $subCategoryIndex = DB::table('sub_categories')
            ->select('id', 'slug', 'category_id')
            ->get()
            ->mapWithKeys(function ($s) {
                return ["{$s->category_id}:{$s->slug}" => $s->id];
            });

        $getCategoryId = function (string $categoryNameOrSlug) use ($categories) {
            $categorySlug = Str::slug($categoryNameOrSlug);
            return $categories[$categorySlug]->id ?? null;
        };

        $getSubCategoryId = function (int $categoryId, string $subNameOrSlug) use ($subCategoryIndex) {
            $subSlug = Str::slug($subNameOrSlug);
            return $subCategoryIndex["{$categoryId}:{$subSlug}"] ?? null;
        };

        // Imagens da galeria (vai alternando pra dar variedade)
        $galleryNumbers = [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30];
        $imageIndex = 0;

        $pickGalleryImage = function () use (&$imageIndex, $galleryNumbers) {
            $num = $galleryNumbers[$imageIndex % count($galleryNumbers)];
            $imageIndex++;

            $base = "backend/assets/images/gallery/{$num}";
            foreach (['.jpg', '.jpeg', '.png', '.webp'] as $ext) {
                if (File::exists(public_path($base . $ext))) {
                    return $base . $ext; // caminho relativo ao /public
                }
            }

            return $base . '.jpg';
        };

        /**
         * CURSOS (garantindo pelo menos 1 por category).
         * Você pode adicionar/remover à vontade.
         */
        $courses = [
            // =======================
            // Development
            // =======================
            [
                'category' => 'Development',
                'subcategory' => 'Programming Languages',
                'course_title' => 'Algoritmos e Lógica de Programação (Do Zero)',
                'course_name' => 'Algoritmos e Lógica de Programação',
                'video_url' => 'https://www.youtube.com/watch?v=8mei6uVttho',
                'label' => 'Beginner',
                'duration' => 8.50,
                'selling_price' => 199,
                'discount_price' => 99,
                'prerequisites' => 'Nenhum. Recomenda-se prática com exercícios.',
                'description' => 'Curso completo para sair do zero em lógica, algoritmos, operadores e resolução de problemas.',
                'resources' => 'PDFs + exercícios + desafios',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Development',
                'subcategory' => 'Web Development',
                'course_title' => 'Web Development: HTML, CSS e JavaScript na Prática',
                'course_name' => 'Web Development Essencial',
                'video_url' => 'https://www.youtube.com/watch?v=kIImolG-C1M',
                'label' => 'Beginner',
                'duration' => 12.00,
                'selling_price' => 249,
                'discount_price' => 129,
                'prerequisites' => 'Nenhum. Editor recomendado: VS Code.',
                'description' => 'Do básico ao prático para criar páginas modernas com responsividade e interatividade.',
                'resources' => 'Projeto guiado + exercícios',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],
            [
                'category' => 'Development',
                'subcategory' => 'Databases',
                'course_title' => 'Banco de Dados Relacionais: Modelagem e SQL',
                'course_name' => 'SQL e Banco de Dados Relacional',
                'video_url' => 'https://www.youtube.com/watch?v=RDrfZ-7WE8c',
                'label' => 'Beginner',
                'duration' => 9.25,
                'selling_price' => 219,
                'discount_price' => 119,
                'prerequisites' => 'Noções básicas de informática e lógica.',
                'description' => 'Modelagem, tabelas, relacionamentos e SQL para consulta e manipulação de dados.',
                'resources' => 'Scripts SQL + desafios',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Development',
                'subcategory' => 'Mobile Development',
                'course_title' => 'React Native com Expo: App do Zero ao Deploy',
                'course_name' => 'React Native com Expo na Prática',
                'video_url' => 'https://www.youtube.com/watch?v=0-S5a0eXPoc',
                'label' => 'Intermediate',
                'duration' => 10.50,
                'selling_price' => 279,
                'discount_price' => 149,
                'prerequisites' => 'JavaScript básico e noções de React ajudam.',
                'description' => 'Construa um app completo com navegação, consumo de API e boas práticas de estrutura.',
                'resources' => 'Projeto completo + templates',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Development',
                'subcategory' => 'Game Development',
                'course_title' => 'Unity para Iniciantes: 2D do Zero',
                'course_name' => 'Game Dev 2D com Unity',
                'video_url' => 'https://www.youtube.com/watch?v=IlKaB1etrik',
                'label' => 'Beginner',
                'duration' => 11.00,
                'selling_price' => 259,
                'discount_price' => 139,
                'prerequisites' => 'Nenhum. Lógica ajuda.',
                'description' => 'Aprenda fundamentos do Unity, sprites, colisão, física e UI criando um jogo 2D.',
                'resources' => 'Assets + projeto final',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],

            // =======================
            // Business
            // =======================
            [
                'category' => 'Business',
                'subcategory' => 'Entrepreneurship',
                'course_title' => 'Empreendedorismo na Prática: Ideia, Validação e MVP',
                'course_name' => 'Empreendedorismo: do Zero ao MVP',
                'video_url' => 'https://www.youtube.com/watch?v=9bZkp7q19f0',
                'label' => 'Beginner',
                'duration' => 6.50,
                'selling_price' => 189,
                'discount_price' => 99,
                'prerequisites' => 'Nenhum.',
                'description' => 'Como validar ideias, entender o problema, definir público-alvo e construir um MVP com foco em aprendizado.',
                'resources' => 'Planilhas + checklists',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Business',
                'subcategory' => 'Management',
                'course_title' => 'Gestão para Times: Rotina, Processos e Resultados',
                'course_name' => 'Gestão e Processos para Equipes',
                'video_url' => 'https://www.youtube.com/watch?v=2cYt9O0oKcE',
                'label' => 'Intermediate',
                'duration' => 7.25,
                'selling_price' => 209,
                'discount_price' => 119,
                'prerequisites' => 'Nenhum.',
                'description' => 'Organize tarefas, rotinas, indicadores e prioridades para aumentar performance do time.',
                'resources' => 'Modelos de processos + templates',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Business',
                'subcategory' => 'Sales',
                'course_title' => 'Vendas: Prospecção, Funil e Fechamento',
                'course_name' => 'Vendas e Funil Comercial',
                'video_url' => 'https://www.youtube.com/watch?v=H14bBuluwB8',
                'label' => 'Beginner',
                'duration' => 5.75,
                'selling_price' => 179,
                'discount_price' => 89,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda a estruturar um funil, abordar clientes, qualificar oportunidades e fechar com consistência.',
                'resources' => 'Scripts de abordagem + planilha de funil',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],

            // =======================
            // Finance & Accounting
            // =======================
            [
                'category' => 'Finance & Accounting',
                'subcategory' => 'Personal Finance',
                'course_title' => 'Finanças Pessoais: Organização, Metas e Controle',
                'course_name' => 'Finanças Pessoais sem Mistério',
                'video_url' => 'https://www.youtube.com/watch?v=Y2VGq3O5q8Q',
                'label' => 'Beginner',
                'duration' => 4.50,
                'selling_price' => 159,
                'discount_price' => 79,
                'prerequisites' => 'Nenhum.',
                'description' => 'Organize gastos, crie metas e controle orçamento com método simples e sustentável.',
                'resources' => 'Planilha de controle financeiro',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Finance & Accounting',
                'subcategory' => 'Accounting',
                'course_title' => 'Contabilidade do Básico ao Prático: Conceitos e Lançamentos',
                'course_name' => 'Contabilidade Essencial',
                'video_url' => 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
                'label' => 'Beginner',
                'duration' => 6.00,
                'selling_price' => 199,
                'discount_price' => 109,
                'prerequisites' => 'Nenhum.',
                'description' => 'Entenda conceitos contábeis, regimes, demonstrações e lançamentos fundamentais.',
                'resources' => 'Exercícios + modelos',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Finance & Accounting',
                'subcategory' => 'Investing',
                'course_title' => 'Investimentos: Renda Fixa e Renda Variável (Iniciante)',
                'course_name' => 'Investimentos para Iniciantes',
                'video_url' => 'https://www.youtube.com/watch?v=lTTajzrSkCw',
                'label' => 'Beginner',
                'duration' => 5.25,
                'selling_price' => 219,
                'discount_price' => 119,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda conceitos de risco, diversificação e produtos mais comuns para iniciar com segurança.',
                'resources' => 'Checklist + simuladores',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],
            [
                'category' => 'Finance & Accounting',
                'subcategory' => 'Financial Modeling',
                'course_title' => 'Modelagem Financeira no Excel: Do Zero',
                'course_name' => 'Modelagem Financeira no Excel',
                'video_url' => 'https://www.youtube.com/watch?v=VqCgcpAypFQ',
                'label' => 'Intermediate',
                'duration' => 8.00,
                'selling_price' => 249,
                'discount_price' => 139,
                'prerequisites' => 'Excel básico recomendado.',
                'description' => 'Monte modelos com premissas, cenários e indicadores para tomada de decisão.',
                'resources' => 'Arquivos Excel + exercícios',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Finance & Accounting',
                'subcategory' => 'Taxes',
                'course_title' => 'Impostos na Prática: Noções e Organização para PF',
                'course_name' => 'Impostos e Organização Financeira',
                'video_url' => 'https://www.youtube.com/watch?v=RgKAFK5djSk',
                'label' => 'Beginner',
                'duration' => 3.75,
                'selling_price' => 149,
                'discount_price' => 69,
                'prerequisites' => 'Nenhum.',
                'description' => 'Entenda conceitos de impostos e como organizar documentos e gastos para evitar dores de cabeça.',
                'resources' => 'Checklist de organização',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '0',
                'status' => 1,
            ],

            // =======================
            // IT & Software
            // =======================
            [
                'category' => 'IT & Software',
                'subcategory' => 'DevOps',
                'course_title' => 'Git e GitHub: Fluxo Profissional do Zero',
                'course_name' => 'Git e GitHub do Zero ao Profissional',
                'video_url' => 'https://www.youtube.com/watch?v=Ig4QZNpVZYs',
                'label' => 'Beginner',
                'duration' => 6.75,
                'selling_price' => 179,
                'discount_price' => 89,
                'prerequisites' => 'Nenhum.',
                'description' => 'Versionamento, branches, merge, pull request e boas práticas para projetos reais.',
                'resources' => 'Cheat sheet + exercícios',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'IT & Software',
                'subcategory' => 'Operating Systems',
                'course_title' => 'Linux Essentials: Terminal, Arquivos e Automação',
                'course_name' => 'Linux Essentials (Terminal e Produtividade)',
                'video_url' => 'https://www.youtube.com/watch?v=N3K8PjFOhy4',
                'label' => 'Beginner',
                'duration' => 7.50,
                'selling_price' => 189,
                'discount_price' => 99,
                'prerequisites' => 'Nenhum.',
                'description' => 'Comandos, permissões, processos e automação básica para quem quer produtividade no Linux.',
                'resources' => 'Lista de comandos + desafios',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '0',
                'highestrated' => '0',
                'status' => 1,
            ],
            [
                'category' => 'IT & Software',
                'subcategory' => 'Network & Security',
                'course_title' => 'Redes e Segurança: Fundamentos para Iniciantes',
                'course_name' => 'Fundamentos de Redes e Segurança',
                'video_url' => 'https://www.youtube.com/watch?v=qiQR5rTSshw',
                'label' => 'Beginner',
                'duration' => 8.25,
                'selling_price' => 229,
                'discount_price' => 129,
                'prerequisites' => 'Nenhum.',
                'description' => 'IP, DNS, HTTP/HTTPS, firewalls e boas práticas de segurança para uso e trabalho.',
                'resources' => 'Mapas mentais + exercícios',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'IT & Software',
                'subcategory' => 'Cloud Computing',
                'course_title' => 'Cloud Computing: Conceitos e Deploy do Zero',
                'course_name' => 'Cloud Computing do Zero',
                'video_url' => 'https://www.youtube.com/watch?v=5gqF3bYI1vo',
                'label' => 'Intermediate',
                'duration' => 9.00,
                'selling_price' => 259,
                'discount_price' => 149,
                'prerequisites' => 'Noções de redes ajudam.',
                'description' => 'Conceitos de cloud, escalabilidade e deploy de aplicações com mentalidade moderna.',
                'resources' => 'Guias + checklist de deploy',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'IT & Software',
                'subcategory' => 'IT Certification',
                'course_title' => 'Certificações em TI: Como Estudar e Passar (Plano Real)',
                'course_name' => 'Plano de Certificações em TI',
                'video_url' => 'https://www.youtube.com/watch?v=OPf0YbXqDm0',
                'label' => 'Beginner',
                'duration' => 4.25,
                'selling_price' => 169,
                'discount_price' => 89,
                'prerequisites' => 'Nenhum.',
                'description' => 'Monte um plano de estudos com método, prática e revisão para certificações de TI.',
                'resources' => 'Planner + cronogramas',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],

            // =======================
            // Office Productivity
            // =======================
            [
                'category' => 'Office Productivity',
                'subcategory' => 'Microsoft Office',
                'course_title' => 'Excel do Zero: Tabelas, Fórmulas e Gráficos',
                'course_name' => 'Excel do Zero ao Prático',
                'video_url' => 'https://www.youtube.com/watch?v=fLexgOxsZu0',
                'label' => 'Beginner',
                'duration' => 9.50,
                'selling_price' => 229,
                'discount_price' => 129,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda Excel com foco no que importa: organização, fórmulas, tabelas dinâmicas e gráficos.',
                'resources' => 'Arquivos para download + exercícios',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Office Productivity',
                'subcategory' => 'Google Workspace',
                'course_title' => 'Google Workspace: Produtividade com Drive, Docs e Sheets',
                'course_name' => 'Produtividade com Google Workspace',
                'video_url' => 'https://www.youtube.com/watch?v=G8Wc6kQwK9Y',
                'label' => 'Beginner',
                'duration' => 5.50,
                'selling_price' => 179,
                'discount_price' => 99,
                'prerequisites' => 'Nenhum.',
                'description' => 'Organize trabalho e estudos com ferramentas do Google: Drive, Docs, Sheets e automações simples.',
                'resources' => 'Templates + checklists',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Office Productivity',
                'subcategory' => 'Project Management',
                'course_title' => 'Gestão de Projetos com Trello: Fluxo Simples e Eficiente',
                'course_name' => 'Gestão de Projetos com Trello',
                'video_url' => 'https://www.youtube.com/watch?v=8ZK_S-46KwE',
                'label' => 'Beginner',
                'duration' => 3.25,
                'selling_price' => 149,
                'discount_price' => 69,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda a organizar tarefas, prioridades e rotinas com um fluxo simples no Trello.',
                'resources' => 'Quadros modelo + checklists',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],

            // =======================
            // Personal Development
            // =======================
            [
                'category' => 'Personal Development',
                'subcategory' => 'Productivity',
                'course_title' => 'Produtividade Real: Rotina, Foco e Execução',
                'course_name' => 'Produtividade e Foco (Método Prático)',
                'video_url' => 'https://www.youtube.com/watch?v=1G4isv_Fylg',
                'label' => 'Beginner',
                'duration' => 4.75,
                'selling_price' => 169,
                'discount_price' => 89,
                'prerequisites' => 'Nenhum.',
                'description' => 'Monte uma rotina sustentável e aprenda técnicas para foco, execução e consistência.',
                'resources' => 'Planner + templates',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Personal Development',
                'subcategory' => 'Leadership',
                'course_title' => 'Liderança: Comunicação, Confiança e Time',
                'course_name' => 'Liderança na Prática',
                'video_url' => 'https://www.youtube.com/watch?v=6Dh-RL__uN4',
                'label' => 'Intermediate',
                'duration' => 6.25,
                'selling_price' => 219,
                'discount_price' => 129,
                'prerequisites' => 'Nenhum.',
                'description' => 'Construa uma liderança baseada em comunicação clara, autonomia e alinhamento.',
                'resources' => 'Modelos de 1:1 + feedback',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Personal Development',
                'subcategory' => 'Career Development',
                'course_title' => 'Carreira: Currículo, LinkedIn e Portfólio',
                'course_name' => 'Carreira e Portfólio Profissional',
                'video_url' => 'https://www.youtube.com/watch?v=7wtfhZwyrcc',
                'label' => 'Beginner',
                'duration' => 5.00,
                'selling_price' => 189,
                'discount_price' => 99,
                'prerequisites' => 'Nenhum.',
                'description' => 'Monte um currículo forte, LinkedIn bem feito e um portfólio que prova suas habilidades.',
                'resources' => 'Templates + checklist',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],
            [
                'category' => 'Personal Development',
                'subcategory' => 'Personal Growth',
                'course_title' => 'Autodesenvolvimento: Hábitos, Consistência e Metas',
                'course_name' => 'Autodesenvolvimento e Hábitos',
                'video_url' => 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
                'label' => 'Beginner',
                'duration' => 4.25,
                'selling_price' => 159,
                'discount_price' => 79,
                'prerequisites' => 'Nenhum.',
                'description' => 'Crie hábitos que duram e organize metas em um sistema simples para evolução contínua.',
                'resources' => 'Planner de hábitos',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],

            // =======================
            // Design
            // =======================
            [
                'category' => 'Design',
                'subcategory' => 'Graphic Design',
                'course_title' => 'Design Gráfico: Fundamentos, Composição e Identidade Visual',
                'course_name' => 'Design Gráfico Essencial',
                'video_url' => 'https://www.youtube.com/watch?v=J---aiyznGQ',
                'label' => 'Beginner',
                'duration' => 7.75,
                'selling_price' => 229,
                'discount_price' => 129,
                'prerequisites' => 'Nenhum.',
                'description' => 'Princípios de design, tipografia, paleta, composição e construção de peças visuais.',
                'resources' => 'Arquivos de exemplo + exercícios',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Design',
                'subcategory' => 'UX/UI',
                'course_title' => 'UX/UI: Wireframes, Protótipos e Design System',
                'course_name' => 'UX/UI do Zero (Produto Digital)',
                'video_url' => 'https://www.youtube.com/watch?v=FTQbiNvZqaY',
                'label' => 'Intermediate',
                'duration' => 9.50,
                'selling_price' => 259,
                'discount_price' => 149,
                'prerequisites' => 'Nenhum.',
                'description' => 'Crie telas com usabilidade, prototipação e um design system consistente.',
                'resources' => 'Templates + projeto prático',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Design',
                'subcategory' => '3D & Animation',
                'course_title' => 'Blender para Iniciantes: Modelagem 3D do Zero',
                'course_name' => 'Modelagem 3D com Blender (Básico)',
                'video_url' => 'https://www.youtube.com/watch?v=TPrnSACiTJ4',
                'label' => 'Beginner',
                'duration' => 6.50,
                'selling_price' => 219,
                'discount_price' => 119,
                'prerequisites' => 'Nenhum.',
                'description' => 'Modelagem, materiais, iluminação e render para começar no 3D com prática guiada.',
                'resources' => 'Arquivos base + exercícios',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '0',
                'status' => 1,
            ],
            [
                'category' => 'Design',
                'subcategory' => 'Design Tools',
                'course_title' => 'Figma: Protótipos e Interfaces Modernas',
                'course_name' => 'Figma do Zero ao Prototipo',
                'video_url' => 'https://www.youtube.com/watch?v=c9Wg6Cb_YlU',
                'label' => 'Beginner',
                'duration' => 5.75,
                'selling_price' => 199,
                'discount_price' => 109,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda Figma com foco em prática: componentes, auto-layout e prototipação.',
                'resources' => 'Arquivo de projeto + exercícios',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],

            // =======================
            // Marketing
            // =======================
            [
                'category' => 'Marketing',
                'subcategory' => 'Digital Marketing',
                'course_title' => 'Marketing Digital: Estratégia, Conteúdo e Conversão',
                'course_name' => 'Marketing Digital do Zero',
                'video_url' => 'https://www.youtube.com/watch?v=60ItHLz5WEA',
                'label' => 'Beginner',
                'duration' => 7.25,
                'selling_price' => 229,
                'discount_price' => 129,
                'prerequisites' => 'Nenhum.',
                'description' => 'Construa um plano simples de marketing com foco em aquisição, conteúdo e conversão.',
                'resources' => 'Planilha + checklists',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Marketing',
                'subcategory' => 'SEO',
                'course_title' => 'SEO na Prática: Ranking, Conteúdo e Técnica',
                'course_name' => 'SEO para Sites e Blogs',
                'video_url' => 'https://www.youtube.com/watch?v=9bZkp7q19f0',
                'label' => 'Intermediate',
                'duration' => 6.25,
                'selling_price' => 219,
                'discount_price' => 119,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda SEO on-page e técnico, pesquisa de palavras-chave e estruturação de conteúdo.',
                'resources' => 'Modelos + checklist SEO',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Marketing',
                'subcategory' => 'Content Marketing',
                'course_title' => 'Conteúdo que Vende: Planejamento e Produção',
                'course_name' => 'Content Marketing (Estratégia e Produção)',
                'video_url' => 'https://www.youtube.com/watch?v=OPf0YbXqDm0',
                'label' => 'Beginner',
                'duration' => 5.00,
                'selling_price' => 189,
                'discount_price' => 99,
                'prerequisites' => 'Nenhum.',
                'description' => 'Planeje, produza e distribua conteúdo com consistência e intenção de conversão.',
                'resources' => 'Calendário editorial + modelos',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '0',
                'status' => 1,
            ],
            [
                'category' => 'Marketing',
                'subcategory' => 'Social Media Marketing',
                'course_title' => 'Social Media: Conteúdo, Reels e Crescimento',
                'course_name' => 'Social Media do Básico ao Avançado',
                'video_url' => 'https://www.youtube.com/watch?v=KQ6zr6kCPj8',
                'label' => 'Beginner',
                'duration' => 6.00,
                'selling_price' => 199,
                'discount_price' => 109,
                'prerequisites' => 'Nenhum.',
                'description' => 'Estratégia para redes sociais, criação de posts, formatos e otimização para crescimento.',
                'resources' => 'Modelos + roteiro de conteúdo',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Marketing',
                'subcategory' => 'Branding',
                'course_title' => 'Branding: Posicionamento, Marca e Consistência',
                'course_name' => 'Branding e Posicionamento de Marca',
                'video_url' => 'https://www.youtube.com/watch?v=6v2L2UGZJAM',
                'label' => 'Intermediate',
                'duration' => 5.50,
                'selling_price' => 219,
                'discount_price' => 129,
                'prerequisites' => 'Nenhum.',
                'description' => 'Construa marca forte com posicionamento, tom de voz e identidade consistente.',
                'resources' => 'Workbook + templates',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],

            // =======================
            // Lifestyle
            // =======================
            [
                'category' => 'Lifestyle',
                'subcategory' => 'Travel',
                'course_title' => 'Viagens Inteligentes: Planejamento, Roteiros e Economia',
                'course_name' => 'Planejamento de Viagens (Roteiro e Orçamento)',
                'video_url' => 'https://www.youtube.com/watch?v=9bZkp7q19f0',
                'label' => 'Beginner',
                'duration' => 3.75,
                'selling_price' => 149,
                'discount_price' => 69,
                'prerequisites' => 'Nenhum.',
                'description' => 'Como planejar viagens com roteiro, orçamento, organização e estratégias para economizar.',
                'resources' => 'Planilhas + modelos de roteiro',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],
            [
                'category' => 'Lifestyle',
                'subcategory' => 'Food & Beverage',
                'course_title' => 'Culinária Prática: Organização e Receitas Base',
                'course_name' => 'Culinária Prática do Dia a Dia',
                'video_url' => 'https://www.youtube.com/watch?v=60ItHLz5WEA',
                'label' => 'Beginner',
                'duration' => 4.00,
                'selling_price' => 159,
                'discount_price' => 79,
                'prerequisites' => 'Nenhum.',
                'description' => 'Técnicas básicas, organização e receitas coringa para o dia a dia.',
                'resources' => 'Lista de compras + receitas',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Lifestyle',
                'subcategory' => 'Arts & Crafts',
                'course_title' => 'Artes & DIY: Projetos Criativos para Iniciantes',
                'course_name' => 'DIY e Artesanato (Projetos Rápidos)',
                'video_url' => 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
                'label' => 'Beginner',
                'duration' => 3.25,
                'selling_price' => 139,
                'discount_price' => 59,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda técnicas simples para criar peças criativas e desenvolver habilidade manual.',
                'resources' => 'Lista de materiais + moldes',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '0',
                'status' => 1,
            ],
            [
                'category' => 'Lifestyle',
                'subcategory' => 'Beauty & Makeup',
                'course_title' => 'Maquiagem do Básico: Pele, Olhos e Finalização',
                'course_name' => 'Maquiagem Básica e Finalização',
                'video_url' => 'https://www.youtube.com/watch?v=KQ6zr6kCPj8',
                'label' => 'Beginner',
                'duration' => 3.50,
                'selling_price' => 149,
                'discount_price' => 69,
                'prerequisites' => 'Nenhum.',
                'description' => 'Técnicas essenciais para preparação de pele, olhos e acabamento.',
                'resources' => 'Guia de produtos + passo a passo',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],

            // =======================
            // Photography & Video
            // =======================
            [
                'category' => 'Photography & Video',
                'subcategory' => 'Photography',
                'course_title' => 'Fotografia: Luz, Composição e Modo Manual',
                'course_name' => 'Fotografia Essencial (Composição e Luz)',
                'video_url' => 'https://www.youtube.com/watch?v=IlKaB1etrik',
                'label' => 'Beginner',
                'duration' => 6.75,
                'selling_price' => 219,
                'discount_price' => 119,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda fotografia com base sólida: composição, luz e configurações essenciais.',
                'resources' => 'Exercícios + guia prático',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Photography & Video',
                'subcategory' => 'Video Editing',
                'course_title' => 'Edição de Vídeo: Corte, Ritmo e Finalização',
                'course_name' => 'Edição de Vídeo do Zero',
                'video_url' => 'https://www.youtube.com/watch?v=fLexgOxsZu0',
                'label' => 'Beginner',
                'duration' => 7.25,
                'selling_price' => 239,
                'discount_price' => 129,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda edição com foco em prática: organização, cortes, áudio e exportação.',
                'resources' => 'Arquivos de treino + presets',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Photography & Video',
                'subcategory' => 'Filmmaking',
                'course_title' => 'Filmmaking: Roteiro, Captação e Direção',
                'course_name' => 'Filmmaking (Do Roteiro à Captação)',
                'video_url' => 'https://www.youtube.com/watch?v=OPf0YbXqDm0',
                'label' => 'Intermediate',
                'duration' => 6.00,
                'selling_price' => 249,
                'discount_price' => 139,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda fundamentos de filmagem com visão prática de roteiro, captação e direção.',
                'resources' => 'Modelos de roteiro + checklist',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],

            // =======================
            // Health & Fitness
            // =======================
            [
                'category' => 'Health & Fitness',
                'subcategory' => 'Fitness',
                'course_title' => 'Treino Inteligente: Hipertrofia e Força para Iniciantes',
                'course_name' => 'Treino de Força para Iniciantes',
                'video_url' => 'https://www.youtube.com/watch?v=1G4isv_Fylg',
                'label' => 'Beginner',
                'duration' => 4.75,
                'selling_price' => 169,
                'discount_price' => 89,
                'prerequisites' => 'Nenhum. Recomenda-se liberação médica se necessário.',
                'description' => 'Aprenda treino de força com técnica e progressão simples para resultados consistentes.',
                'resources' => 'Planilha de treino + guias',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Health & Fitness',
                'subcategory' => 'Nutrition',
                'course_title' => 'Nutrição na Prática: Hábitos e Planejamento Alimentar',
                'course_name' => 'Nutrição e Planejamento Alimentar',
                'video_url' => 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
                'label' => 'Beginner',
                'duration' => 4.25,
                'selling_price' => 179,
                'discount_price' => 99,
                'prerequisites' => 'Nenhum.',
                'description' => 'Monte hábitos alimentares melhores com planejamento e escolhas sustentáveis.',
                'resources' => 'Cardápios modelo + checklist',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Health & Fitness',
                'subcategory' => 'Mental Health',
                'course_title' => 'Saúde Mental: Rotina, Estresse e Autocuidado',
                'course_name' => 'Saúde Mental e Autocuidado',
                'video_url' => 'https://www.youtube.com/watch?v=KQ6zr6kCPj8',
                'label' => 'Beginner',
                'duration' => 3.50,
                'selling_price' => 159,
                'discount_price' => 79,
                'prerequisites' => 'Nenhum.',
                'description' => 'Estratégias práticas para lidar com estresse, rotina e autocuidado com consistência.',
                'resources' => 'Planner + exercícios guiados',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],
            [
                'category' => 'Health & Fitness',
                'subcategory' => 'Yoga',
                'course_title' => 'Yoga para Iniciantes: Mobilidade e Respiração',
                'course_name' => 'Yoga para Iniciantes',
                'video_url' => 'https://www.youtube.com/watch?v=VqCgcpAypFQ',
                'label' => 'Beginner',
                'duration' => 3.75,
                'selling_price' => 149,
                'discount_price' => 69,
                'prerequisites' => 'Nenhum.',
                'description' => 'Comece no yoga com práticas simples para mobilidade, respiração e bem-estar.',
                'resources' => 'Rotinas guiadas + calendário',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],

            // =======================
            // Music
            // =======================
            [
                'category' => 'Music',
                'subcategory' => 'Music Production',
                'course_title' => 'Produção Musical: Beats, Mixagem e Arranjo',
                'course_name' => 'Produção Musical do Zero',
                'video_url' => 'https://www.youtube.com/watch?v=RgKAFK5djSk',
                'label' => 'Beginner',
                'duration' => 7.00,
                'selling_price' => 239,
                'discount_price' => 129,
                'prerequisites' => 'Nenhum.',
                'description' => 'Fundamentos de produção musical: ritmo, estrutura, mixagem básica e finalização.',
                'resources' => 'Projetos + presets',
                'certificate' => 'yes',
                'bestseller' => '1',
                'featured' => '1',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Music',
                'subcategory' => 'Instruments',
                'course_title' => 'Violão para Iniciantes: Acordes, Ritmo e Músicas',
                'course_name' => 'Violão para Iniciantes',
                'video_url' => 'https://www.youtube.com/watch?v=2Vv-BfVoq4g',
                'label' => 'Beginner',
                'duration' => 6.25,
                'selling_price' => 199,
                'discount_price' => 109,
                'prerequisites' => 'Nenhum.',
                'description' => 'Aprenda acordes, batidas e progressões para tocar suas primeiras músicas com confiança.',
                'resources' => 'Cifras + exercícios',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '0',
                'highestrated' => '1',
                'status' => 1,
            ],
            [
                'category' => 'Music',
                'subcategory' => 'Music Theory',
                'course_title' => 'Teoria Musical: Notas, Escalas e Harmonia',
                'course_name' => 'Teoria Musical Essencial',
                'video_url' => 'https://www.youtube.com/watch?v=ktvTqknDobU',
                'label' => 'Beginner',
                'duration' => 5.50,
                'selling_price' => 219,
                'discount_price' => 119,
                'prerequisites' => 'Nenhum.',
                'description' => 'Entenda teoria musical com prática: escalas, intervalos, acordes e progressões.',
                'resources' => 'Exercícios + material de apoio',
                'certificate' => 'yes',
                'bestseller' => '0',
                'featured' => '1',
                'highestrated' => '0',
                'status' => 1,
            ],
        ];

        foreach ($courses as $c) {
            $categoryId = $getCategoryId($c['category'] ?? '');
            if (!$categoryId) {
                continue;
            }

            $subCategoryId = $getSubCategoryId((int) $categoryId, $c['subcategory'] ?? '');
            if (!$subCategoryId) {
                continue;
            }

            $slug = Str::slug($c['course_name'] ?? $c['course_title'] ?? Str::random(10));

            DB::table('courses')->updateOrInsert(
                ['course_name_slug' => $slug],
                [
                    'category_id' => (int) $categoryId,
                    'subcategory_id' => (int) $subCategoryId,
                    'instructor_id' => (int) $instructorId,

                    'course_image' => $pickGalleryImage(),
                    'course_title' => $c['course_title'] ?? null,
                    'course_name' => $c['course_name'] ?? null,
                    'course_name_slug' => $slug,

                    'description' => $c['description'] ?? null,
                    'video_url' => $c['video_url'] ?? null,
                    'label' => $c['label'] ?? null,

                    'resources' => $c['resources'] ?? null,
                    'certificate' => $c['certificate'] ?? null,

                    'duration' => $c['duration'] ?? null,
                    'selling_price' => $c['selling_price'] ?? null,
                    'discount_price' => $c['discount_price'] ?? null,
                    'prerequisites' => $c['prerequisites'] ?? null,

                    'bestseller' => $c['bestseller'] ?? '0',
                    'featured' => $c['featured'] ?? '0',
                    'highestrated' => $c['highestrated'] ?? '0',

                    'status' => $c['status'] ?? 0,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }
}
